### ISSUE TITLE
No module named glass.modeling.rotated_rpn

### ISSUE THREAD

**Issue by xiaoruiai** [amazon-research/glass-text-spotting#2]

**Comment by tsiper** [comment]
Hi, thanks for flagging this issue, we are currently testing the fix, I'll update once we push an update. You should expect it in the next couple of days

**Comment by milely** [comment]
Hi, may I ask when will the complete code be updated? Thanks in advance.

**Comment by tsiper** [comment]
Hi, the updated code have just been pushed, thanks again for the interest in our work!
